apiVersion: cert-manager.k8s.io/v1
kind: Certificate
metadata:
  name: noontown-com-tls
spec:
  secretName: noontown-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: noontown.com
  dnsNames:
    - noontown.com
    - www.noontown.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - noontown.com
          - www.noontown.com