apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: noontown-com-tls
spec:
  secretName: noontown-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - noontown.com
    - www.noontown.com
  privateKey:
    rotationPolicy: Always
  # acme: # not in 1.4 or below
  #   config:
  #     - http01:
  #         ingressClass: nginx
  #       domains:
  #         - noontown.com
  #         - www.noontown.com